/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 head_white.glb --transform 
Files: head_white.glb [761.9KB] > head_white-transformed.glb [79.46KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/head_white-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FaceBuilderHead002.geometry} material={materials.material_1} position={[-2.016, 1.352, 0.613]} rotation={[1.544, 0.019, 0.022]} scale={1.5} />
    </group>
  )
}

useGLTF.preload('/head_white-transformed.glb')
