/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 cloud.glb --transform 
Files: cloud.glb [25.57MB] > cloud-transformed.glb [2.5MB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cloud(props) {
  const { nodes, materials } = useGLTF('./loaders/cloud-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube003.geometry} material={materials.PaletteMaterial001} position={[41.794, -5.071, -80.236]} scale={[16.091, 5.495, 5.797]} />
    </group>
  )
}

useGLTF.preload('./cloud/cloud-transformed.glb')
