/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 colorfulHeadsBorder.glb --transform 
Files: colorfulHeadsBorder.glb [63.42MB] > colorfulHeadsBorder-transformed.glb [13.36MB] (79%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HeadBorder(props) {
  const { nodes, materials } = useGLTF('./loaders/colorfulHeadsBorder-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FaceBuilderHead004.geometry} material={materials.PaletteMaterial001} position={[-129.977, 0, 0]} rotation={[1.677, 0.026, 0.017]} scale={1.404} />
    </group>
  )
}

useGLTF.preload('./loaders/colorfulHeadsBorder-transformed.glb')
export default HeadBorder;